name: pr

on:
  pull_request:
    branches: [ main ]

env:
  SOURCE_PATH: "zipzup-web"
  APP_NAME: "zipzup"
  GRADLE_OPTS: "-Dfile.encoding=UTF-8"

jobs:
  pr-check:
    runs-on: ubuntu-20.04
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: build test
        run: |
          ./gradlew clean check --parallel
      - name: archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: zipzup-web/build/reports/
